- Cargo.toml
- src/lib.rs
- src/page.rs
Fixes resolution of relative and absolute links.
> Fix link resolution

- README.md
- src/configuration.rs
- src/website.rs
Adds polite delay as configuration.
> Add polite delay

- src/configuration.rs
- src/page.rs
- src/website.rs
Minor changes suggested by clippy.
> Minor refactor

- examples/Cargo.toml
- spider/Cargo.toml
- spider_cli/Cargo.toml
1. minor description adjustment for crate to match readme root
2. add j-mendez to authors
> chore(minor): match crate description readme

- examples/Cargo.toml
- spider/Cargo.toml
- spider_cli/Cargo.toml
> Revert "chore(minor): match crate description readme"

- spider/src/page.rs
- spider/src/website.rs
1. Fix memory release after crawl job
2. Reduce memory usage by using references
3. Fix 2021 assertion test handling (format! deprecation)
> Memory release

- spider/src/configuration.rs
1. add UA setting from cargo package configs. (easier incremental updates).
> chore(ua): add cargo env ua defaults

- spider/src/configuration.rs
- spider/src/website.rs
> chore(log): add log util

- spider/src/page.rs
- spider/src/website.rs
- spider_cli/src/main.rs
1. add link gathering in thread spawn.
1. add cli ignore storing the page into memory.
-----------------------------------------------------------------
> perf(parsing): add async parallel page handling

- benches/crawl.rs
- examples/Cargo.toml
- examples/stack.rs
- spider/Cargo.toml
- spider/src/website.rs
- spider_cli/src/main.rs
- spider_cli/src/options/sub_command.rs
1. add stack buffer crawl api 
```
website.crawl_stack(None);
```
-- notes
This improves the base crawl api slightly by allowing par_extend onto links inserting.
> feat(crawl): add stack buffer crawl imp

- examples/example.rs
- examples/stack.rs
- spider/Cargo.toml
- spider/src/configuration.rs
- spider/src/lib.rs
- spider/src/website.rs
- spider_cli/src/main.rs
- spider_cli/src/options/args.rs
1. remove configuration verbose for default imp of logger
> chore(log): add crate log default logger

- benches/Cargo.toml
- examples/Cargo.toml
- spider/Cargo.toml
- spider/README.md
- spider/src/configuration.rs
- spider/src/website.rs
- spider_cli/Cargo.toml
1. remove setup from public api (only should be called internally).
1. add detection for simultaneous multithreading
> chore(concurrency): add simultaneous multithreading detection

- spider/src/configuration.rs
1. inc default pool limit
-- action run perf
> perf(concurrency): increase default concurrency limit

- benches/Cargo.toml
- benches/build.rs
- benches/crawl.rs
- examples/Cargo.toml
- examples/example.rs
- spider/Cargo.toml
- spider/README.md
- spider/src/lib.rs
- spider/src/page.rs
- spider/src/website.rs
- spider_cli/Cargo.toml
- spider_cli/README.md
* add ALPN tls ( fixes connections auth and enables increased perf preventing extra round trips )
* add brotli compression defaults
* remove macro static css selector usage preventing unsafe control
* update tokio to latest "^1.20.1"
> chore(req): add ALPN TLS default

- Cargo.lock
- README.md
- benches/BENCHMARKS.md
- examples/Cargo.toml
- examples/debug.rs
- examples/download.rs
- examples/download_to_react.rs
- examples/example.rs
- examples/scrape.rs
- spider/Cargo.toml
- spider/README.md
- spider/src/configuration.rs
- spider/src/lib.rs
- spider/src/packages/robotparser.rs
- spider/src/page.rs
- spider/src/utils.rs
- spider/src/website.rs
- spider_cli/Cargo.toml
- spider_cli/README.md
- spider_cli/src/main.rs
- spider_cli/src/options/args.rs
> feat(runtime): add async crawl handling

- Cargo.lock
- README.md
- examples/Cargo.toml
- spider/Cargo.toml
- spider/README.md
- spider/src/lib.rs
- spider/src/website.rs
- spider_cli/Cargo.toml
- spider_cli/README.md
* add `par_iter` collection extending
> feat(rayon): add rayon par_iter usage

- .github/workflows/bench.yml
- Cargo.lock
- benches/Cargo.toml
- examples/Cargo.toml
- examples/debug.rs
- examples/download.rs
- examples/download_to_react.rs
- examples/example.rs
- examples/scrape.rs
- spider/Cargo.toml
- spider/README.md
- spider/src/configuration.rs
- spider/src/lib.rs
- spider/src/packages/robotparser.rs
- spider/src/website.rs
- spider_cli/Cargo.toml
- spider_cli/README.md
- spider_cli/src/main.rs
* feat jemalloc memory backend
--
optional support to use jemalloc to improve performance on dedicated crawls.
> feat(mem): add jemalloc opt memory backend

- Cargo.lock
- examples/Cargo.toml
- spider/Cargo.toml
- spider/README.md
- spider/src/lib.rs
- spider/src/page.rs
- spider/src/website.rs
- spider_cli/Cargo.toml
- spider_cli/README.md
* add fast page selector builder
* improve page containing ( reduces memory used - large crawls it adds up )
* fix tld test case
--
> perf(crawl): add performant string handling

- examples/Cargo.toml
- spider/Cargo.toml
- spider/README.md
- spider/src/website.rs
- spider_cli/Cargo.toml
- spider_cli/README.md
increase performance over 30% and reduce memory footprint.
> perf(crawl): add improved runtime yielding

- Cargo.lock
- examples/Cargo.toml
- spider/Cargo.toml
- spider/README.md
- spider/src/packages/robotparser.rs
- spider/src/page.rs
- spider/src/website.rs
- spider_cli/Cargo.toml
- spider_cli/README.md
- spider_cli/src/main.rs
crate-less example.
https://github.com/spider-rs/spider/pull/88
> perf(links): add ascii case-insensitive handling

- Cargo.lock
- examples/Cargo.toml
- examples/example.rs
- spider/Cargo.toml
- spider/README.md
- spider/src/website.rs
- spider_cli/Cargo.toml
- spider_cli/README.md
1. store active crawl links on the heap
> chore(crawl): add heap links_visited usage

- CHANGELOG.md
- Cargo.lock
- examples/Cargo.toml
- spider/Cargo.toml
- spider/README.md
- spider/src/lib.rs
- spider/src/page.rs
- spider/src/website.rs
- spider_cli/Cargo.toml
- spider_cli/README.md
- spider_cli/src/main.rs
1. perf(crawl): add join handle task management 
-- 
major memory reduction and perf improvements for x large scans.
> perf(crawl): add join handle task management

- Cargo.lock
- examples/Cargo.toml
- spider/Cargo.toml
- spider/README.md
- spider/src/packages/scraper/html/tree_sink.rs
- spider/src/packages/scraper/mod.rs
- spider/src/packages/scraper/node.rs
- spider/src/packages/scraper/selector.rs
- spider/src/page.rs
- spider/src/website.rs
- spider_cli/Cargo.toml
- spider_cli/README.md
- spider_cli/src/main.rs
1. perf(parser): add concurrent streaming parser implementation
1. perf(parser): add ego tree walk imp for extreme speeds
-- Notes
If the ego tree walking is default without concurrency the output is beyond fast. If you do not need concurrency adding an option could be added.
> perf(parser): add fast concurrency setup

- .github/workflows/rust.yml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- examples/Cargo.toml
- spider/Cargo.toml
- spider/README.md
- spider/src/page.rs
- spider/src/utils.rs
- spider/src/website.rs
- spider_cli/Cargo.toml
- spider_cli/README.md
- spider_cli/src/main.rs
- spider_worker/Cargo.toml
- spider_worker/README.md
- spider_worker/src/main.rs
- tests/profile.rs
1. add link gathering decentralization
> perf(decentralized): add link gathering decentralization

- spider/src/website.rs
- spider_worker/src/main.rs
1. add worker semaphore limiting
1. http1 remove keep alive
> perf(workers): add increased semaphore limits

- Cargo.lock
- examples/Cargo.toml
- spider/Cargo.toml
- spider/README.md
- spider/src/configuration.rs
- spider/src/lib.rs
- spider/src/website.rs
- spider_cli/Cargo.toml
- spider_cli/README.md
- spider_worker/Cargo.toml
1. perf regex set one pass string
2. fix regex test
> perf(regex): use regex set one pass

- Cargo.lock
- examples/Cargo.toml
- examples/download.rs
- examples/download_to_react.rs
- spider/Cargo.toml
- spider/README.md
- spider/src/page.rs
- spider_cli/Cargo.toml
- spider_worker/Cargo.toml
Fix crawling from subdomains entry to base domain.
> chore(page): fix subdomain entry point handling root

- Cargo.lock
- examples/Cargo.toml
- spider/Cargo.toml
- spider/README.md
- spider/src/features/cron.rs
- spider/src/features/mod.rs
- spider/src/lib.rs
- spider/src/website.rs
- spider_cli/Cargo.toml
- spider_worker/Cargo.toml
Use cron syntax to perform crawls in the background at any time.
> feat(cron): add cron feature flag

- CHANGELOG.md
- Cargo.lock
- README.md
- examples/Cargo.toml
- examples/README.md
- examples/smart.rs
- spider/Cargo.toml
- spider/README.md
- spider/src/lib.rs
- spider/src/page.rs
- spider/src/utils.rs
- spider/src/website.rs
- spider_cli/Cargo.toml
- spider_worker/Cargo.toml
This feature provides running intelligent scans that run HTTP initially and falling back to Chrome Rendering if needed.
1. smart mode provides the fastest way to crawl websites without missing content. Runs HTTP first until Javascript Rendering is required.
1. fix chrome finding links
1. improve crawl performance remove extra external domain clones
> Smart mode

- .gitignore
- Cargo.lock
- examples/Cargo.toml
- spider/Cargo.toml
- spider/README.md
- spider/src/lib.rs
- spider/src/packages/robotparser/parser.rs
- spider/src/page.rs
- spider/src/utils.rs
- spider/src/website.rs
- spider_cli/Cargo.toml
- spider_worker/Cargo.toml
- spider_worker/src/main.rs
*  feat(cache): add caching backend feat flag
> feat(cache): add caching backend feat flag

- spider/README.md
> Fix typo in README file

- spider_cli/src/main.rs
- spider_cli/src/options/args.rs
Fixing short names that prevented running #195
> Fixing clap issues #195

- spider/src/utils/mod.rs
Exits loop if bytestream returns error
> Fix infinite loop

- spider/src/lib.rs
Fixes https://github.com/spider-rs/spider/issues/253
> docs: fix unclear documentation around scraping

- examples/chrome_remote.rs
> chrome_remote.rs: Add note about headless-browser
