- src/page.rs
This is my attempt at handling page get errors.
PS: I am new to Rust and my proposition might not be the best.
> Handle page get errors

- Cargo.toml
- src/configuration.rs
- src/lib.rs
- src/page.rs
- src/website.rs
This adds the ability to set one's own user agent or simply fall back to library's default UA; spider.
PS: This PR contains automated formatting changes.
> Add User Agent configuration

- src/page.rs
Drop URL fragment (hash) from absolute path of extracted links.
If left, spider might crawl the same page multiple times since fragments (hashes) makes it look like a different web page.
> Drop URL fragment from absolute path

- Cargo.toml
- README.md
- src/website.rs
1. fix on_link_find_callback type ( #test ignore types).
1. fix docs example missing semi-colon.
> fix(crawl): fix field type

- README.md
- src/main.rs
1. add ability to run crawler via cli
-- all options available except `user_agent` and `on_link_find_callback`
example
cargo run -- --domain https://choosealicense.com --verbose true --delay 2000
> feat(cli): add cli ability

- Cargo.lock
- Cargo.toml
- README.md
- example.rs
- src/configuration.rs
- src/lib.rs
- src/website.rs
1. dynamically check cpus to use for concurrency as default: increase parallelism default performance 
1. move link callback to thread (performance boost)
- performance
initial tests ran at about 8s
afterwards test ran at about 3s
> feat(concurrency): dynamic concurrent cpu defaults

- CHANGELOG.md
- examples/example.rs
- spider/Cargo.toml
- spider/src/lib.rs
- spider/src/website.rs
1. fix robotsparser getting crawl_delay
1. fix robotsparser assign user agent for request to extract the `robots.txt` file. Different from configuration.user_agent used to extract the agent entry in the file.
1. fix reading robots.txt action unless `self.configuration.respect_robots_txt` is enabled.
-- notes
The robotsparser repo looks a little dead and the library did not publish version 0.11.0 on the docs which has some drastic differences on how we handle the parsing. Made a test fork here https://github.com/j-mendez/robotparser-rs/commits/master. The fork starts off at 10.2 the latest version and patches up the issue on respect the entry casing for `Crawl-delay` amongst other properties and additional features like req UA setting.
> feat(robots): add robots crawl delay respect and ua assign

- CHANGELOG.md
- spider/Cargo.toml
- spider/src/lib.rs
- spider/src/page.rs
- spider/src/website.rs
1. add peer matching tokio to crate deps.
- rayon uses tokio in a dep but, the package does not re-export the runtime for usage outside, requires us to install ontop. This does not duplicate the package installation.
2. move html content to async call
3. update rust edition for async
-- screenshot of tokio being used in main prior to PR.
robotparser package has tokio as a dev dep, can view it here [robotparser](https://github.com/messense/robotparser-rs/blob/master/Cargo.toml).
https://github.com/madeindjs/spider/issues/21
> feat(async): add async page body gathering

- CHANGELOG.md
- spider/Cargo.toml
- spider/src/lib.rs
- spider/src/page.rs
- spider/src/utils.rs
- spider/src/website.rs
1. re-use connections across request (major latency improvement)
1. remove auto drop values (fix easy re-crawling without needing to re-instantiate )
1. add invalid crawl test case to make sure program does not exit
1. upgrade rayon latest
> perf(latency): add connection re-use across request

- CHANGELOG.md
- spider/src/page.rs
1. fix valid selecting of page anchors.
2. drastic performance boost on getting valid links for domain.
---------------------------------------
45s shaved off the test runs.
Prior 
test finish around 2.89s
After 
test finish around 2.4s
Relates to https://github.com/madeindjs/spider/pull/29.
> chore(links): fix parsing valid website pages

- .github/workflows/rust.yml
- CHANGELOG.md
- examples/Cargo.toml
- spider/Cargo.toml
- spider/src/configuration.rs
- spider/src/lib.rs
- spider/src/website.rs
- spider_cli/Cargo.toml
1. add regex black list option
-- notes
atm `in_list` uses references. Might make sense to add as trait.
https://github.com/madeindjs/spider/issues/32
> feat(regex): add optional regex black listing

- spider/src/configuration.rs
- spider/src/utils.rs
- spider/src/website.rs
1. improve crawl performance by skipping O(N) initial filter and need of additional copy from filter. ( few ms shaved on small pages website, more impactful on large crawls ).
> perf(crawl): improve crawl link exclusion

- .github/workflows/bench.yml
- benches/.gitignore
- benches/Cargo.toml
- benches/crawl.rs
- benches/go_crolly.rs
- examples/Cargo.toml
- spider/Cargo.toml
- spider/src/page.rs
- spider/src/utils.rs
- spider/src/website.rs
- spider_cli/Cargo.toml
1. fix mixing async runtime with blocking dispatch causing use of reqwest pool_max_idle_per_host which does not dispatch properly upon the async task completion outside the current thread. 
-- TODO
Move `crawl` to fully async api with `crawl_sync` or blocking counter part.
Now the sync bench marks can properly be compared against node, go, and rust for crawling.
> perf(client): fix blocking and async mixture

- benches/Cargo.toml
- examples/Cargo.toml
- spider/Cargo.toml
- spider/src/website.rs
- spider_cli/Cargo.toml
1. add async delay tasks scheduling for true non blocking delayed calls between pages.
--
This brings time differences between the delays between pages for true time elapsing between request.
Also  drastic perf boosts for keeping machine alive and using async scheduling.
Todo:
1. use async client and move entire tasks into tokio runtime.
1. instead of choosing the runtime for the spawn it should be optional with defaults.
ss of req running per delay.
> feat(delay): add non blocking delay scheduling

- benches/Cargo.toml
- examples/Cargo.toml
- spider/Cargo.toml
- spider/README.md
- spider/src/lib.rs
- spider/src/page.rs
- spider_cli/Cargo.toml
1. adds full media resource ignore list.
1. move evaluation to const out of runtime for non dynamic selectors
1. bump v1.7.14
> fix(selectors): add resources to ignore list to handle main formats

- README.md
- benches/Cargo.toml
- examples/Cargo.toml
- spider/Cargo.toml
- spider/README.md
- spider/src/page.rs
- spider/src/website.rs
- spider_cli/Cargo.toml
- spider_cli/src/main.rs
- spider_cli/src/options/sub_command.rs
1. add multi threaded html scraping ability and expose html for extracting.
-----
example of `--output-links` and `--output-html` sub commands for the new `scrape` API. Examples use `> res.json` to pipe the output to a file. 
output with links
```
spider  --domain https://a11ywatch.com scrape --output-links > res.json
```
output with html
```
spider  --domain https://a11ywatch.com scrape --output-links --output-html > res.json
```
> feat(scrape): add html scrape ability

- examples/Cargo.toml
- examples/example.rs
- spider/Cargo.toml
- spider/README.md
- spider/src/configuration.rs
- spider/src/page.rs
- spider/src/website.rs
- spider_cli/Cargo.toml
- spider_cli/README.md
- spider_cli/src/main.rs
- spider_cli/src/options/args.rs
* add subdomain crawling ability
* add tld crawling ability
Collectively allows for gathering all pages that relate to a website bare host name with all `.` or tld extenstion or `subdomains` without sacrificing speed on crawl.
```rust
use spider::website::Website;
fn main() {
let mut website: Website = Website::new("https://a11ywatch.com"); 
website.configuration.subdomains = true;
}
```
-- 
Examples of output to validate since current test cases / examples do not use subdomains.
Before 25 links on the domain [a11ywatch.com](https://a11ywatch.com) -
After 50+ links on the domain [a11ywatch.com](https://a11ywatch.com) -
--
~~This pr combines two features into one - subdomains and tld ignoring. It might make sense moving `tld` to a different variable and option since anyone can own a tld …
> feat(crawl): add subdomain and tld crawling

- benches/BENCHMARKS.md
- benches/build.rs
- benches/crawl.rs
- benches/go_crolly.rs
- benches/node_crawler.rs
* add concurrent benches 10x
-- 
Benches are done on a small sized website with 15 pages. 
On the url `https://rsseau.fr`.
|   simultaneous                                       | `libraries`               |
| :--------------------------------------- | :------------------------ |
| **`Rust[spider]: crawl 10 samples`**     | `1.8375 s` (✅ **1.00x**) |
| **`Go[crolly]: crawl 10 samples`**       | `2.9417 s` (✅ **1.00x**) |
| **`Node.js[crawler]: crawl 10 samples`** | `2.9992 s` (✅ **1.00x**) |
| **`C[wget]: crawl 10 samples`**          | `12.019 s` (✅ **1.00x**) |
|     concurrent                                     | `libraries`                |
| :--------------------------------------- | :------------------------- |
| **`Rust[spider]: crawl 10 samples`**     | `2.8644 s` (✅ **10.00x**) | …
> bench(crawl): add concurrent benches

- examples/Cargo.toml
- spider/Cargo.toml
- spider/README.md
- spider/src/packages/robotparser.rs
- spider/src/website.rs
- spider_cli/Cargo.toml
- spider_cli/README.md
The reference imp of the robot parser causes leaks on runs due to the static lifetimes.
-- The crawler is setup to only handle pages that are in the UI.
We need to switch the parser to use https://github.com/Folyd/robotstxt and remove the reference imp.
Some more details why below:
https://doc.rust-lang.org/book/ch15-06-reference-cycles.html
> chore(memory): fix memory leaks on robot parser

- spider_cli/src/main.rs
Got 2 compiler warnings (using Rust LSP in Emacs)
1. Usage of unwrap_or followed by a function call. [Fix](https://deepsource.io/directory/analyzers/rust/issues/RS-W1031)
2. delimiter in split was a single character string. Changed to char.
> Compiler Warnings

- Cargo.lock
- examples/Cargo.toml
- examples/example.rs
- spider/Cargo.toml
- spider/README.md
- spider/src/configuration.rs
- spider/src/website.rs
- spider_cli/Cargo.toml
- spider_cli/README.md
1. add client configs for large scanning
Local mac m1 results avg
```
Time elapsed in website.crawl() is: 153.99869s for total pages: 23198
Command being timed: "./target/release/examples/example"
User time (seconds): 78.69
System time (seconds): 16.48
Percent of CPU this job got: 61%
Elapsed (wall clock) time (h:mm:ss or m:ss): 2:34.50
Average shared text size (kbytes): 0
Average unshared data size (kbytes): 0
Average stack size (kbytes): 0
Average total size (kbytes): 0
Maximum resident set size (kbytes): 1498576
Average resident set size (kbytes): 0
Major (requiring I/O) page faults: 24
Minor (reclaiming a frame) page faults: 457897
Voluntary context switches: 25774
Involuntary context switches: 566372
Swaps: 0
File system inputs: 0
File system outputs: 0
Socket messages sent: 167475 …
```
> perf(client): add mass scan configs

- .github/workflows/bench.yml
- benches/Cargo.toml
- benches/build.rs
- benches/crawl.rs
- benches/crawl_massive.rs
- spider/README.md
Test `spider_worker` split runtime handling bytes processing bench. The worker in a real world case would not be on the same machine for the most part.
Leveraging the worker to split the IO/CPU work across two runtimes seems to balance out well.
—
Spider with the worker benches around 10k pages per min on the small GitHub action runner. Drastically faster than the default.
> bench(decentralized): add decentralized worker split case

- Cargo.lock
- spider/Cargo.toml
- spider/README.md
- spider/src/page.rs
Add the ability to parse javascript to extract links created. Use the feature flag `js` to enable parsing.
The current implementation uses a recursive lib that needs the `RUST_MIN_STACK` env variable increased.
Set `RUST_MIN_STACK=9999999` or run in release mode when using the js flag.
Example of a link extracted with the [jsdom](https://github.com/a11ywatch/jsdom) crate.
```rust
use std::collections::HashSet;
use jsdom::extract::extract_links;
const SCRIPT: &str = r###"
var ele = document.createElement('a');
ele.href = 'https://a11ywatch.com';
"###;
#[test]
fn parse_links() {
// build tree with elements created from the nodes todo
let links: HashSet<String> = extract_links(SCRIPT);
assert!(links.contains("https://a11ywatch.com"))
}
```
> feat(js): add init of script parsing

- spider/README.md
Hi, I tried using the example in the "scrape/gather html" section but to no success. 
I added `.iter()` to the for each loop and it worked. 
I'm new to Rust, so I'm not sure, if there is a better method.
> docs(fix): fix error in "scrape/gather html" section

- spider/src/page.rs
- spider/src/utils.rs
When a request returns an error status, the resulting page will always contain the default status code (200). This change will return the actual status code.
> Return status code on error

- examples/README.md
- Fix broken url for glob example
> docs: fix broken glob url link

- spider_cli/src/options/args.rs
> chore(cli): trigger help page on missing arguments

- Cargo.lock
- examples/Cargo.toml
- examples/chrome_remote_tls.rs
- spider/Cargo.toml
- spider_chrome/Cargo.toml
This addresses an issue when using a remote Chrome connection over `wss:` instead of `ws:` or `http:`. I'm unsure if it aligns with the repository's conventions, so please let me know if any adjustments are needed.
Related issue in chromiumoxide: https://github.com/mattsse/chromiumoxide/issues/249
> feat(chrome): add support for wss connection

- spider_chrome/src/handler/network.rs
Currently when calling `page.authenticate` there is issues on https://abrahamjuliot.github.io/creepjs/ with certain window property values not being able to be read.
Original solution was mentioned in this pr https://github.com/mattsse/chromiumoxide/pull/247
> fix: errors with page.authenticate

- spider/src/configuration.rs
A small quality of life improvement for those of us that want to define configurations in external files so we don't need to specify all of the `Configuration` fields.
Thanks!
> Add serde(default) for Configuration.
